const tables=[20000,30000,40000,50000,50000,60000,70000,80000,90000,100000];
let wallet=1000000,currentTable=null,bank=0,banker=0,bankRound=1,players=[],deck=[],activePlayer=1;
let bankerHand=[],playerHand=[],playerDone=false,bankerTurn=false,askechi=true,dealTimer=null,battleSettled=false,bankerDrewThisHand=false,handBetPlaced=false;
const names=["بازیکن ۱","بازیکن ۲","بازیکن ۳","بازیکن ۴","بازیکن ۵","بازیکن ۶"];
const $=id=>document.getElementById(id),money=n=>n.toLocaleString("fa-IR");
const fullDeck=()=>{const a=[];for(let s=0;s<4;s++)for(const c of ["6","7","8","9","10","J","Q","K","A"])a.push(c);return a};
function shuffle(){deck=fullDeck();for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}}
function draw(){return deck.pop()}
function value(c){return c==="A"?11:c==="J"?2:c==="Q"?3:c==="K"?4:Number(c)}
function score(hand){let total=hand.reduce((a,c)=>a+value(c),0),aces=hand.filter(c=>c==="A").length;while(total>21&&aces--)total-=10;return total}
function cardVisual(c){const map={"6":"🂦","7":"🂧","8":"🂨","9":"🂩","10":"🂪","J":"🂫","Q":"🂭","K":"🂮","A":"🂡"};return `<span class="playing-card" title="${c}">${map[c]||c}</span>`}
function cardsText(hand){return hand.map(cardVisual).join("")}
function renderTables(){$("tables").innerHTML=tables.map((base,i)=>{const ok=wallet>=base*4;return `<article class="table-card"><h3>میز ${i+1}</h3><div class="amount">${money(base)} تومان</div><div class="meta">حداقل موجودی: ${money(base*4)} تومان<br>ظرفیت: ۲ تا ۶ نفر</div><button class="join" ${ok?"":"disabled"} onclick="joinTable(${i})">${ok?"ورود به میز":"موجودی کافی نیست"}</button></article>`}).join("");$("wallet").textContent=money(wallet)}
function joinTable(i){currentTable=i;bank=tables[i]*3;bankRound=1;players=names.map(name=>({name,hand:[],done:false,balance:1000000}));banker=null;activePlayer=0;shuffle();$("modalTitle").textContent=`میز ${i+1}`;$("tableInfo").textContent=`مبلغ پایه: ${money(tables[i])} تومان | بانک اولیه: ${money(bank)} تومان`;$("modal").classList.remove("hidden");startAskechi()}
function startAskechi(){askechi=true;banker=null;bankerHand=[];playerHand=[];players.forEach(p=>p.hand=[]);shuffle();const start=Math.floor(Math.random()*players.length);activePlayer=start;renderAskechi(start);dealAskechi(start)}
function renderAskechi(current){$("bankAmount").textContent=money(bank);$("status").textContent="آس‌کشی";$("handInfo").innerHTML="";$("cardChoices").innerHTML="";$("standBtn").style.display="none";$("nextRoundBtn").style.display="none";$("seats").innerHTML=players.map((p,i)=>`<div class="seat s${i} ${i===current?"active":""}"><div class="avatar">👤</div><div class="name">${p.name}</div><div class="tag">${i===current?"نوبت آس‌کشی":""}</div><div class="cards">${p.hand.length?cardsText(p.hand):"—"}</div></div>`).join("")}
function dealAskechi(index){clearTimeout(dealTimer);dealTimer=setTimeout(()=>{const c=draw();players[index].hand.push(c);renderAskechi(index);if(c==="A"){banker=index;dealTimer=setTimeout(()=>{askechi=false;activePlayer=(banker+1)%players.length;$("standBtn").style.display="block";$("nextRoundBtn").style.display="block";$("tableInfo").textContent=`مبلغ پایه: ${money(tables[currentTable])} تومان | بانکدار: ${players[banker].name} | دور بانکداری: ۱ از ۳`;startBankingRound();},900);return}dealAskechi((index+1)%players.length)},800)}
function startBankingRound(){shuffle();players.forEach(p=>{p.hand=[];p.done=false});playerHand=[];playerDone=false;bankerTurn=false;battleSettled=false;bankerDrewThisHand=false;handBetPlaced=false;activePlayer=(banker+1)%players.length;for(let i=0;i<players.length;i++){const idx=(banker+1+i)%players.length;players[idx].hand.push(draw())}bankerHand=[draw()];render();beginPlayer()}
function beginPlayer(){if(activePlayer===banker){nextPlayer();return}const base=tables[currentTable];if(players[activePlayer].balance<base){players[activePlayer].done=true;nextPlayer();return}players[activePlayer].balance-=base;handBetPlaced=true;bankerDrewThisHand=false;playerHand=[...players[activePlayer].hand];playerDone=false;bankerTurn=false;battleSettled=false;render();if(score(playerHand)>=21)finishPlayer()}
function render(){if(askechi)return;$("bankAmount").textContent=money(bank);const base=tables[currentTable];const chipCount=Math.max(0,Math.min(12,Math.round(bank/base)));$("bankChips").textContent="🪙".repeat(chipCount)||"—";$("status").textContent=bankerTurn?"نوبت بانکدار":`نوبت ${players[activePlayer].name}`;$("seats").innerHTML=players.map((p,i)=>`<div class="seat s${i} ${i===banker?"banker ":""} ${i===activePlayer&&!bankerTurn?"active":""}"><div class="avatar">${i===banker?"👑":"👤"}</div><div class="name">${p.name}</div><div class="tag">${i===banker?"بانکدار":""}</div><div class="cards">${i===banker?cardsText(bankerHand):i===activePlayer?cardsText(playerHand):"🂠"}</div><div class="seat-balance">موجودی: ${money(p.balance)} تومان</div></div>`).join("");$("handInfo").innerHTML=bankerTurn?`دست بانکدار: <strong>${cardsText(bankerHand)}</strong> — ${score(bankerHand)}`:`دست بازیکن فعال: <strong>${cardsText(playerHand)}</strong> — ${score(playerHand)}`;renderChoices()}
function renderChoices(){const box=$("cardChoices");box.innerHTML="";if(bankerTurn){const b=document.createElement("button");b.textContent="کارت بعدی";b.onclick=bankDraw;box.appendChild(b);return}for(let n=1;n<=4;n++){const b=document.createElement("button");b.textContent=`${n} کارت`;b.onclick=()=>requestCards(n);box.appendChild(b)}}
function requestCards(n){if(bankerTurn||playerDone)return;for(let i=0;i<n;i++){playerHand.push(draw());if(score(playerHand)>21)break}players[activePlayer].hand=[...playerHand];render();if(score(playerHand)>21||score(playerHand)===21)finishPlayer()}
function stand(){if(bankerTurn||playerDone)return;playerDone=true;players[activePlayer].hand=[...playerHand];bankerPlay()}
function finishPlayer(){if(playerDone)return;playerDone=true;players[activePlayer].hand=[...playerHand];const ps=score(playerHand);if(ps>=21){finishBattle(ps===21?"player21":"playerBust");return}bankerPlay()}
function bankerPlay(){bankerTurn=true;render();const bs=score(bankerHand),ps=score(playerHand);if(ps>21){finishBattle("playerBust");return}if(bs>21||bs===21){finishBattle();return}if(bs>=17){finishBattle();return}}
function bankDraw(){if(!bankerTurn)return;bankerHand.push(draw());bankerDrewThisHand=true;render();if(score(bankerHand)>21||score(bankerHand)>=17)finishBattle()}
function finishBattle(reason="normal"){if(battleSettled)return;battleSettled=true;const base=tables[currentTable];const ps=score(playerHand),bs=score(bankerHand);const playerWins=reason==="player21"||(reason!=="playerBust"&&ps<=21&&ps>bs);if(playerWins){bank=Math.max(0,bank-base);players[activePlayer].balance+=base*2;$("status").textContent=`${players[activePlayer].name} برنده شد • ${money(base)} تومان از بانک گرفت`;}else{bank+=base;$("status").textContent=`بانکدار برنده شد • ${money(base)} تومان به بانک اضافه شد`;}$("bankAmount").textContent=money(bank);players[activePlayer].hand=[];playerHand=[];if(bankerDrewThisHand)bankerHand=[];handBetPlaced=false;if(bank<=0||bank>=base*9){$("cardChoices").innerHTML="";render();return}render();setTimeout(nextPlayer,500)}
function nextPlayer(){let next=(activePlayer+1)%players.length;if(next===banker)next=(next+1)%players.length;if(next===banker){endBankRound();return}activePlayer=next;playerHand=[];playerDone=false;bankerTurn=false;render();setTimeout(beginPlayer,250)}
function endBankRound(){if(bank>=tables[currentTable]*9||bankRound>=3){$("cardChoices").innerHTML="";return}$("cardChoices").innerHTML="";$("status").textContent="دور تمام شد"}
function newBankRound(){if(bankRound>=3||bank>=tables[currentTable]*9)return;bankRound++;$("tableInfo").textContent=`مبلغ پایه: ${money(tables[currentTable])} تومان | بانکدار: ${players[banker].name} | دور بانکداری: ${bankRound} از ۳`;startBankingRound()}
function bankMenu(){document.getElementById("sideMenu").classList.toggle("open");document.getElementById("menuOverlay").classList.toggle("show")}
$("standBtn").onclick=stand;$("nextRoundBtn").onclick=newBankRound;$("closeModal").onclick=()=>$("modal").classList.add("hidden");$("modal").addEventListener("click",e=>{if(e.target===$("modal"))$("modal").classList.add("hidden")});
$("chatBtn").onclick=toggleChat;$("voiceBtn").onclick=toggleVoice;$("sendChat").onclick=sendChat;$("chatInput").addEventListener("keydown",e=>{if(e.key==="Enter")sendChat()});$("menuBtn").onclick=bankMenu;$("menuClose").onclick=bankMenu;$("menuOverlay").onclick=bankMenu;$("rulesBtn").onclick=()=>{$("rulesModal").classList.remove("hidden");bankMenu()};$("rulesClose").onclick=()=>$("rulesModal").classList.add("hidden");
renderTables();
function toggleChat(){document.getElementById("chatPanel").classList.toggle("hidden")}function toggleVoice(){const b=document.getElementById("voiceBtn");b.classList.toggle("active");b.textContent=b.classList.contains("active")?"🎙 وویس روشن":"🎙 وویس";document.getElementById("voiceNote").textContent=b.classList.contains("active")?"وویس روشن است؛ برای گفت‌وگوی واقعی چندنفره باید اتصال آنلاین WebRTC اضافه شود.":"وویس خاموش است."}function sendChat(){const input=document.getElementById("chatInput"),t=input.value.trim();if(!t)return;const x=document.createElement("div");x.className="chat-msg";x.textContent="شما: "+t;document.getElementById("chatMessages").appendChild(x);input.value=""}